### ISSUE TITLE
Clean up Support Call TA Form design

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1251] opened 2017-09-08 21:27 UTC
![screen shot 2017-09-08 at 10 06 24 am](https://user-images.githubusercontent.com/77445/30231852-c9be1764-94a1-11e7-9c05-59fce75f4f6c.png)

**Comment by ltwheeler** [comment] 2017-11-27 20:01
Duplicate of #1450

**Closed by ltwheeler** 2017-11-27 20:01 UTC
Labels: enhancement
