### ISSUE TITLE
JS Exception: action.payload.teachingAssignments.forEach is not a function

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1392] opened 2017-10-31 19:43 UTC
URL: https://ipa.ucdavis.edu/teachingCalls/13/2017/teachingCall User: Sparapani, Nicole Kerberos: njsparap Full Error: action.payload.teachingAssignments.forEach is not a function Stack: _pageStateReducers@https://ipa.ucdavis.edu/js/teachingCallApp.js?rel=1509399455548:6:18017 reduce@https://ipa.ucdavis.edu/js/teachingCallApp.js?rel=1509399455548:6:19469 removePreference/<@https://ipa.ucdavis.edu/js/teachingCallApp.js?rel=1509399455548:6:10099 processQueue@https://ipa.ucdavis.edu/js/lib.js:14:6272 scheduleProcessQueue/<@https://ipa.ucdavis.edu/js/lib.js:14:6539 $eval@https://ipa.ucdavis.edu/js/lib.js:14:19934 $digest@https://ipa.ucdavis.edu/js/lib.js:14:17619 $apply@https://ipa.ucdavis.edu/js/lib.js:14:20361 scheduleApplyAsync/applyAsyncId<@https://ipa.ucdavis.edu/js/lib.js:14:13023 completeOutstandingRequest@https://ipa.ucdavis.edu/js/lib.js:11:8144 Browser/self.defer/timeoutId<@https://ipa.ucdavis.edu/js/lib.js:11:11273

**Comment by ltwheeler** [comment] 2017-10-31 22:00
Was able to reproduce this by:
As an instructor, creating multiple preferences for the same course in the teaching call form,
As an AC, Approving one of the preferences,
As an instructor attempting to delete the unapproved preference.

Caused by a bug in the backend route, fixed in ipa-web.

**Closed by ltwheeler** 2017-10-31 22:00 UTC
Labels: bug, high priority
